version: "3"

services:
  backend:
    image: node:16
    container_name: ebytr_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    ports:
      - 3001:3001
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    environment:
      - PORT=3001
      - DATABASE_HOST=ebytr_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password_ebytr
      - DATABASE_NAME=Ebytr
      - JWT_SECRET=senhasupersecretahihi
  db:
    image: mysql:8.0.21
    container_name: ebytr_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password_ebytr
    restart: always

networks:
  default:
    name: ebytr_net