DROP DATABASE IF EXISTS Ebytr;

CREATE DATABASE Ebytr;

USE Ebytr;

CREATE TABLE Users (
  `id` VARCHAR(30) NOT NULL PRIMARY KEY,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `admin` BOOLEAN NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL
) ENGINE=INNODB;

CREATE TABLE Tasks (
  `id` VARCHAR(30) NOT NULL PRIMARY KEY,
  `title` VARCHAR(30) NOT NULL,
  `priority` INT NOT NULL,
  `user_id` VARCHAR(30) NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES Users(`id`)
) ENGINE=INNODB;

SET SQL_SAFE_UPDATES = 0;